# ORM table model package — imported here to ensure all models are registered
# on Base.metadata before Alembic autogenerate inspects it.
from ddm_v2.models.domain import (  # noqa: F401
    AuditLogRow,
    ComponentLibraryRow,
    EmployeeRow,
    FromLocationRow,
    GloveRuleRow,
    IonFanBindingRow,
    LevelEntryRow,
    LevelGuidelineRow,
    LevelSystemTemplateRow,
    LocationLibraryRow,
    MINamingRuleRow,
    MostWorkspaceRow,
    ObjectLibraryRow,
    PrecautionRow,
    PrecautionRuleRow,
    ProjectRow,
    ReferencePointRow,
    SimulationResultRow,
    SopActionRow,
    SopVersionRow,
    StationRow,
    SyntaxLibraryRow,
    ToLocationRow,
    ToolLibraryRow,
    UserRow,
)
