"""initial_schema

Revision ID: 9ca79ab8d9f7
Revises: 
Create Date: 2026-03-26 19:05:22.566035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ca79ab8d9f7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('component_library',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name_cn', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employees',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('station_type', sa.String(length=64), nullable=False),
    sa.Column('skill_level', sa.String(length=32), nullable=False),
    sa.Column('efficiency_factor', sa.Float(), nullable=False),
    sa.Column('certifications', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('from_locations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('glove_rules',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('object_category', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('glove_type', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ion_fan_bindings',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('object_category', sa.String(length=128), nullable=False),
    sa.Column('object_name', sa.String(length=255), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('level_entries',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('scope_key', sa.String(length=255), nullable=False),
    sa.Column('action_id', sa.String(length=64), nullable=False),
    sa.Column('difficulty_factor', sa.Float(), nullable=False),
    sa.Column('number_tag', sa.String(length=64), nullable=True),
    sa.Column('number_count', sa.Integer(), nullable=True),
    sa.Column('main_seq', sa.String(length=64), nullable=True),
    sa.Column('order_seq', sa.String(length=64), nullable=True),
    sa.Column('cub_group', sa.String(length=64), nullable=True),
    sa.Column('machine_count', sa.Integer(), nullable=False),
    sa.Column('operator_count', sa.Integer(), nullable=False),
    sa.Column('status_label', sa.String(length=128), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope_key', 'action_id', name='uq_level_entry_scope_action')
    )
    op.create_index(op.f('ix_level_entries_scope_key'), 'level_entries', ['scope_key'], unique=False)
    op.create_table('level_guidelines',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('level_system_templates',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location_library',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mi_naming_rules',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('field', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('most_workspaces',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('sop_version_id', sa.String(length=64), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_most_workspaces_project_id'), 'most_workspaces', ['project_id'], unique=False)
    op.create_index(op.f('ix_most_workspaces_sop_version_id'), 'most_workspaces', ['sop_version_id'], unique=False)
    op.create_table('object_library',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=False),
    sa.Column('sub_category', sa.String(length=128), nullable=True),
    sa.Column('glove_type', sa.String(length=128), nullable=True),
    sa.Column('ctq', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('precaution_rules',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('trigger_type', sa.String(length=32), nullable=False),
    sa.Column('trigger_value', sa.String(length=255), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('precautions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('process', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=128), nullable=True),
    sa.Column('version', sa.String(length=64), nullable=True),
    sa.Column('process_type', sa.String(length=64), nullable=True),
    sa.Column('factory', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reference_points',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulation_results',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.String(length=64), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_results_project_id'), 'simulation_results', ['project_id'], unique=False)
    op.create_table('stations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('employee_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('syntax_library',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('action_verb', sa.String(length=128), nullable=False),
    sa.Column('code_most', sa.String(length=16), nullable=False),
    sa.Column('parameter_range', sa.String(length=64), nullable=False),
    sa.Column('tmu_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('to_locations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tool_library',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('spec', sa.String(length=255), nullable=False),
    sa.Column('bit', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    op.create_table('sop_versions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('version_no', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.String(length=64), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_by', sa.String(length=64), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sop_versions_project_id'), 'sop_versions', ['project_id'], unique=False)
    op.create_table('sop_actions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('sop_version_id', sa.String(length=64), nullable=False),
    sa.Column('sort_idx', sa.Integer(), nullable=False),
    sa.Column('seq_type', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tmu', sa.Integer(), nullable=False),
    sa.Column('seconds', sa.Float(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('precautions', sa.JSON(), nullable=False),
    sa.Column('equipment_params', sa.JSON(), nullable=True),
    sa.Column('station_id', sa.String(length=64), nullable=True),
    sa.Column('component', sa.String(length=255), nullable=True),
    sa.Column('tool', sa.String(length=255), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('is_ctq', sa.Boolean(), nullable=False),
    sa.Column('primary_action', sa.String(length=255), nullable=True),
    sa.Column('hand', sa.String(length=32), nullable=True),
    sa.Column('object_category', sa.String(length=128), nullable=True),
    sa.Column('glove_type', sa.String(length=128), nullable=True),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.Column('level_tag', sa.String(length=128), nullable=True),
    sa.Column('is_simo', sa.Boolean(), nullable=False),
    sa.Column('simo_group_id', sa.String(length=64), nullable=True),
    sa.Column('required_skill', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['sop_version_id'], ['sop_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sop_actions_sop_version_id'), 'sop_actions', ['sop_version_id'], unique=False)
    op.create_index(op.f('ix_sop_actions_sort_idx'), 'sop_actions', ['sort_idx'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sop_actions_sort_idx'), table_name='sop_actions')
    op.drop_index(op.f('ix_sop_actions_sop_version_id'), table_name='sop_actions')
    op.drop_table('sop_actions')
    op.drop_index(op.f('ix_sop_versions_project_id'), table_name='sop_versions')
    op.drop_table('sop_versions')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('tool_library')
    op.drop_table('to_locations')
    op.drop_table('syntax_library')
    op.drop_table('stations')
    op.drop_index(op.f('ix_simulation_results_project_id'), table_name='simulation_results')
    op.drop_table('simulation_results')
    op.drop_table('reference_points')
    op.drop_table('projects')
    op.drop_table('precautions')
    op.drop_table('precaution_rules')
    op.drop_table('object_library')
    op.drop_index(op.f('ix_most_workspaces_sop_version_id'), table_name='most_workspaces')
    op.drop_index(op.f('ix_most_workspaces_project_id'), table_name='most_workspaces')
    op.drop_table('most_workspaces')
    op.drop_table('mi_naming_rules')
    op.drop_table('location_library')
    op.drop_table('level_system_templates')
    op.drop_table('level_guidelines')
    op.drop_index(op.f('ix_level_entries_scope_key'), table_name='level_entries')
    op.drop_table('level_entries')
    op.drop_table('ion_fan_bindings')
    op.drop_table('glove_rules')
    op.drop_table('from_locations')
    op.drop_table('employees')
    op.drop_table('component_library')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
